const FEED_POSTS = 'feedPosts'
const BEST_POSTS = 'bestPosts'

const CATEGORY_POSTS = '_CATEGORY_POSTS'

const USER = 'USER'
const USER_ID = 'USER_'
const USER_POSTS_BY = 'USER_POSTS_BY_'

export { FEED_POSTS, BEST_POSTS, CATEGORY_POSTS, USER, USER_ID, USER_POSTS_BY }